import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import data from "../data/3.17.0/skilltree/data.json";
import { SkillTreeData, AssetLoadedSkillTreeData } from "../types/skilltree";
import SkillTree from "../components/SkillTree";
import loadSkillTreeAssets from "../components/SkillTree/loadSkillTreeAssets";

const skillTree: SkillTreeData = data as SkillTreeData;
console.log(skillTree);

const Home: NextPage = () => {
  const [assetLoadedSkillTree, setAssetLoadedSkillTree] =
    useState<AssetLoadedSkillTreeData | null>(null);

  useEffect(() => {
    loadSkillTreeAssets(skillTree).then((loadedTree) =>
      setAssetLoadedSkillTree(loadedTree)
    );
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {assetLoadedSkillTree ? (
          <SkillTree skillTree={assetLoadedSkillTree} />
        ) : (
          <h1>Loading...</h1>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
